"""Tests for the Report Conductor's deterministic core.

No model calls: these lock the parts that must be trustworthy — the report skeletons, the
fact gathering (which is the ground truth the model may only phrase), and the markdown
composition. The per-section prose is the model's job and isn't asserted here.
"""

from __future__ import annotations

from newton.index import RepoIndex
from newton.memory import Memory
from newton.report.conductor import (
    REPORT_SPECS,
    _is_generated,
    compose_report,
    gather_facts,
)
from newton.tools import ToolBelt


def test_is_generated_filters_build_noise():
    assert _is_generated("frontend/package-lock.json")
    assert _is_generated("frontend/dist/assets/index-abc.js")
    assert _is_generated("backend/src/newton.egg-info/SOURCES.txt")
    assert not _is_generated("backend/src/newton/report/conductor.py")
    assert not _is_generated("frontend/src/App.tsx")


# --- report skeletons -------------------------------------------------------

def test_report_specs_integrity():
    filenames = set()
    valid_keys = {"overview", "tree", "stats", "modules", "git",
                  "progress", "decisions", "phases", "memory", "todos"}
    for name, spec in REPORT_SPECS.items():
        assert spec.title and spec.filename
        assert spec.filename not in filenames, "report filenames must be unique"
        filenames.add(spec.filename)
        assert spec.sections, f"{name} has no sections"
        for title, instruction, keys in spec.sections:
            assert title and instruction
            assert keys and set(keys) <= valid_keys, f"{name}/{title} references unknown fact keys"


# --- deterministic fact gathering ------------------------------------------

def test_gather_facts_reads_real_project(tmp_path):
    (tmp_path / "README.md").write_text("# Demo\nA small demo project.\n", encoding="utf-8")
    (tmp_path / "app.py").write_text("def main():\n    pass  # TODO: implement\n", encoding="utf-8")
    index = RepoIndex(tmp_path).build()
    facts = gather_facts(
        tmp_path, index, Memory(tmp_path / ".newton" / "memory.jsonl"), ToolBelt(tmp_path)
    )
    assert "demo" in facts["overview"].lower()
    assert "app.py" in facts["tree"]
    assert "files" in facts["stats"]
    assert "app.py" in facts["modules"]
    assert facts["git"] == ""                      # tmp_path is not a git repo → empty, not error
    assert "TODO" in facts["todos"]
    assert facts["memory"] == ""                   # no memory written yet


def test_gather_facts_absent_sources_are_empty(tmp_path):
    (tmp_path / "only.py").write_text("x = 1\n", encoding="utf-8")
    index = RepoIndex(tmp_path).build()
    facts = gather_facts(
        tmp_path, index, Memory(tmp_path / ".newton" / "memory.jsonl"), ToolBelt(tmp_path)
    )
    assert facts["overview"] == "" and facts["decisions"] == "" and facts["progress"] == ""
    # keys always present so section assembly never KeyErrors
    for key in ("overview", "tree", "stats", "modules", "git", "progress",
                "decisions", "phases", "memory", "todos"):
        assert key in facts


# --- markdown composition ---------------------------------------------------

def test_compose_report_structure():
    spec = REPORT_SPECS["status"]
    out = compose_report(spec, "demo", "ollama:qwen2.5-coder:7b",
                         [("Summary", "It works."), ("Open Items", "None.")])
    assert out.startswith("# Project Status Report — demo")
    assert "Generated by Newton" in out
    assert "## Summary\n\nIt works." in out
    assert "## Open Items\n\nNone." in out
